### ISSUE TITLE
[feature] Version PSCI and install it to Powershell modules instead of copying it every time it's needed

### ISSUE THREAD

**Issue by mgr32** [ObjectivityLtd/PSCI#28]

**Comment by sergeytunnik** [comment]
This is must have.
For now I put PSCI in PowerShell modules and pass this path into PSCILibraryPath.

**Comment by mgr32** [comment]
Do you think you could use version that's available at powershell gallery? If not, could you describe in more details how you're using PSCI? 
We're considering writing a new version and such input would be welcome :)

**Comment by sergeytunnik** [comment]
Hi.
Yes, using version from powershell gallery is perfect. But right now there is only 1.0.4 version there (https://www.powershellgallery.com/packages/PSCI/1.0.4). And on github and nuget there is 1.10.0 (https://www.nuget.org/packages/PSCI/1.0.10).
OOB deploy.ps downloads latest version form nuget into local packages folder.
We call deploy.ps from TFS release management. During each release TFS cleanups working folder and gets latest artifacts. And I don't really want to spend deployment time on downloading tools from the internet. And in some configuration access to internet may be restricted.
So I put latest version into windows powershell modules folder on TFS agent machine and call deploy.ps this way:
```
$releaseRootPath = $env:AGENT_RELEASEDIRECTORY
$releaseEnvironmnet = $env:RELEASE_ENVIRONMENTNAME

# Configuration
$psciProjectPath = Join-Path -Path $releaseRootPath -ChildPath 'MyDeployer\drop'
$psciLibraryPath = 'C:\Program Files\WindowsPowerShell\Modules\PSCI'
$psciPackages = (New-Item -Path (Join-Path -Path $releaseRootPath -ChildPath 'MyPackages') -ItemType Directory -Force).FullName

# Execute deployment
&$psciProjectPath\deploy.ps1 -ProjectRootPath $psciProjectPath -PSCILibraryPath $psciLibraryPath -PackagesPath $psciPackages -Environment $releaseEnvironmnet
```
More straightforward way in deploy.ps would look something like:
```
if (-not (Get-Module -Name 'PSCI' -ListAvailable)) {
    Install-Module -Name 'PSCI'
}
Import-Module 'PSCI'
```
Also I'm strong supporter of idea no to store external dependencies in source control and just install them as they needed. Just add them in psd1:
```
RequiredModules = @('Carbon')
```
And then check module existence and install it. WMF 5 looks really good. I think it's useful to utilize modules management that comes with it now instead of plain nuget. :)
Regarding SQLPSX module there is dbatools module (https://github.com/sqlcollaborative/dbatools) worth checking.

**Comment by mgr32** [comment]
Thanks for that and sorry for late response, your comment landed in junk e-mail.
We'll update powershell gallery with the latest version of PSCI and we're certainly going to use WMF5 capabilities / RequiredModules in PSCI2 and look into dbatools :) Please let us know if you have any other suggestions.

**Comment by mgr32** [comment]
Done in version [1.1.5](https://github.com/ObjectivityLtd/PSCI/releases/tag/1.1.5), available at PSGallery.
